services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: socmed_honoridezc
    ports:
      - "3306:3306"
  web:
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    user: root
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db